### ISSUE TITLE
How to calibrate IMU and camera extrinsinc parameters?

### ISSUE THREAD

**Issue by Cathy-YC** [shishiteng/VINS-Stereo#2]
您好！我也发现初始化时固定camera-imu之间的位置参数更容易导致漂移，怀疑是相机和IMU外参标定的问题，请问您是怎么标定的呀？另外怎么判断标定有没有问题？多谢！

**Comment by shishiteng** [comment]
@Cathy-YC You can calibrate cam-imu extrincscs with Kalibr(https://github.com/ethz-asl/kalibr)，the calibration report is very very detailed.
