### ISSUE TITLE
使用optor相机这个工程已经达到了一个稳定的效果吗？

### ISSUE THREAD

**Issue by gangyahaidao** [shishiteng/VINS-Stereo#3]
你好，感谢开源了这么好的一个视觉框架工程
原来使用optor相机测试了一下港科的([(https://github.com/HKUST-Aerial-Robotics/VINS-Mono)](https://github.com/HKUST-Aerial-Robotics/VINS-Mono))，漂移问题有点严重，看到你的这个工程是在这个的基础上有了很大的优化，想问下这个工程目前可以使用optor或者boteye相机进行使用测试了吗？感谢

**Comment by shishiteng** [comment]
@gangyahaidao 可以的
