### ISSUE TITLE
有没有考虑加入ICE-BA的功能呢？

### ISSUE THREAD

**Issue by gangyahaidao** [shishiteng/VINS-Stereo#4]
最近百度开源的产品ICE-BA对后端优化有很大的改进，作者有没有考虑在工程中加入此功能呢？
参考[https://github.com/baidu/ICE-BA](https://github.com/baidu/ICE-BA)

**Comment by shishiteng** [comment]
@gangyahaidao 考虑过，但是要等我有时间。

**Comment by gangyahaidao** [comment]
期待大神的成果，感谢
